### ISSUE TITLE
Namespace Change?

### ISSUE THREAD

**Issue by aolszowka** [vestervang/DotNet-BlueZ#3]
I am totally fine with keeping all of the ProrepubliQ naming if we want; but if we want to have this be the generic library going forward might we consider renaming this to something more generic? Or switching to the name of the maintainer as in `vestervang.DotNet-BlueZ`?

If we start pushing this up to NuGet we're going to get name conflicts with the previous package unless we do something about it?

**Comment by vestervang** [comment]
I have just created a PR for changing the name space. https://github.com/vestervang/DotNet-BlueZ/pull/2

**Comment by vestervang** [comment]
The PR has been merged
