### ISSUE TITLE
Issue With DeviceFoundEventArgs.Device.GetAllAsync()

### ISSUE THREAD

**Issue by aolszowka** [vestervang/DotNet-BlueZ#8]
Consider the following test program (also available as a branch off of my Fork here - https://github.com/aolszowka/DotNet-BlueZ/tree/ako-DevicePropertiesBug):

**Program.cs**
```csharp
using vestervang.DotNetBlueZ;
// using HashtagChris.DotNetBlueZ;
using System.Diagnostics;

namespace DevicePropertiesGetAllAsync
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var adapter = (await BlueZManager.GetAdaptersAsync()).FirstOrDefault())
            {
                try
                {
                    if (adapter != null)
                    {
                        adapter.DeviceFound += adapter_DeviceFoundAsync;

                        var props = new Dictionary<string, object>();
                        props.Add("Transport", "le");
                        props.Add("DuplicateData", false);
                        await adapter.SetDiscoveryFilterAsync(props);
                        await adapter.StartDiscoveryAsync();
                        Console.WriteLine("Waiting for events. Use Control-C to quit.");
                        await Task.Delay(-1);
                    }
                    else
                    {
                        Console.Error.WriteLine("Failed to get the Adapter; Exiting");
                        Environment.ExitCode = -1;
                    }
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine(ex);
                }
                finally
                {
                    Console.WriteLine("Stopping Discovery");
                    if (adapter != null)
                    {
                        await adapter.StopDiscoveryAsync();
                    }
                }
            }
        }

        private static async Task adapter_DeviceFoundAsync(Adapter sender, DeviceFoundEventArgs eventArgs)
        {
            Console.WriteLine("A device was found!");
            var deviceProperties = await eventArgs.Device.GetAllAsync();
            Console.WriteLine($"{deviceProperties.Name} ({deviceProperties.Address}) was the device.");
        }
    }
}
```

**DevicePropertiesGetAllAsync.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNetBlueZ.csproj"/>
    <!-- <PackageReference Include="HashtagChris.DotNetBlueZ" Version="1.3.1" /> -->
  </ItemGroup>
</Project>
```

When running on a Raspberry Pi 4B off of the latest version of this code from GitHub I get the following output:

```
Waiting for events. Use Control-C to quit.
A device was found!
A device was found!
 () was the device.
A device was found!
 () was the device.
A device was found!
 () was the device.
 () was the device.
A device was found!
 () was the device.
A device was found!
 () was the device.
A device was found!
 () was the device.
```

When I comment out the use of this library and attempt to use the original fork I get the information I expect (I have redacted the Addresses and parts of the names, but all of the data is legitimate):

```
Waiting for events. Use Control-C to quit.
A device was found!
A device was found!
Encharg/xxxx (04:0D:84:xx:xx:xx) was the device.
Encharg/xxxx (04:0D:84:xx:xx:xx) was the device.
A device was found!
Enpower/xxxx (54:0F:57:xx:xx:xx) was the device.
A device was found!
Encharg/xxxx (04:0D:84:xx:xx:xx) was the device.
A device was found!
TP357 (xxxx) (BC:C7:DA:xx:xx:xx) was the device.
```

I suspect this has something to do with the additional logic that as added for caching, but I do not understand enough about the changes to know where to start debugging this. Can anyone else reproduce this issue or confirm if this is just related to the Pi?

**Comment by vestervang** [comment]
It's not just on the Raspberry Pi 4B, I have recreated the issue on my own machine. I'll have a look at it

**Comment by vestervang** [comment]
The issue only seems to affect the `Device.GetAllAsync()` method. I tried to remove the device caching and got the same results. If I'm using the extensions methods the data is retrieved correctly. Are the extensions methods working correctly for you?

**Comment by aolszowka** [comment]
Thank you for taking the time to look at this issue.

> Are the extensions methods working correctly for you?

If I understand your question correctly I believe the following toy program should provide a reasonable test of this ability, on my Pi this still fails. In this case the `var devices = await adapter.GetDevicesAsync();` never appears to return any devices, despite seeing several devices fly by on `sudo btmon`.

Here's the sample program:

**Program.cs**
```csharp
using vestervang.DotNetBlueZ;

namespace AdapterExtensionsGetAllDevicesAsync
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var adapter = (await BlueZManager.GetAdaptersAsync()).FirstOrDefault())
            {
                try
                {
                    if (adapter != null)
                    {
                        var props = new Dictionary<string, object>();
                        props.Add("Transport", "le");
                        props.Add("DuplicateData", false);
                        await adapter.SetDiscoveryFilterAsync(props);
                        await adapter.StartDiscoveryAsync();
                        Console.WriteLine("Waiting for devices. Use Control-C to quit.");
                        while (true)
                        {
                            var devices = await adapter.GetDevicesAsync();
                            foreach (var device in devices)
                            {
                                var deviceProperties = await device.GetAllAsync();
                                Console.WriteLine($"{deviceProperties.Name} ({deviceProperties.Address}) was the device.");
                            }
                        }
                    }
                    else
                    {
                        Console.Error.WriteLine("Failed to get the Adapter; Exiting");
                        Environment.ExitCode = -1;
                    }
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine(ex);
                }
                finally
                {
                    Console.WriteLine("Stopping Discovery");
                    if (adapter != null)
                    {
                        await adapter.StopDiscoveryAsync();
                    }
                }
            }
        }

    }
}
```

**AdapterExtensionsGetAllDevicesAsync.csproj**
```csharp
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNetBlueZ.csproj"/>
  </ItemGroup>
</Project>
```

Again these are available here: https://github.com/aolszowka/DotNet-BlueZ/tree/ako-DevicePropertiesBug/manualTests/AdapterExtensionsGetAllDevicesAsync I would be happy to create a PR to merge in these changes into the manual tests once we've figured out the root cause to have more examples/test programs.

Were you thinking of something else?

**Comment by vestervang** [comment]
Figuered out the issue. The problem was a new syntax in the DBusInterfaces.cs file. Try the branch from this PR: https://github.com/vestervang/DotNet-BlueZ/pull/9

Edit: If you didn't know, the package is on nuget now https://www.nuget.org/packages/vestervang.DotNetBlueZ

**Comment by aolszowka** [comment]
@vestervang bingo; this works for me. However in order to build locally I needed to change the `LangVersion` tag to `latest` as opposed to `11`. This is because I do not have the .NET 7 SDK (there is not an Ubuntu provided package that I am aware of). Would you be willing to settle for that as opposed to a specific version? This is officially supported/documented as per https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version. You do not appear to be using any of the new C# 11 Language features (as this builds).

Regardless I can still consume the NuGet package as you're targeting netstandard2.0 (thank you!)

Would you like me to open a PR to include the manual tests I mentioned above? I'd be happy to contribute them to this project!

**Comment by vestervang** [comment]
dotnet 7 should be in the ubuntu 22.10 feed, 22.04 only has dotnet 6. Anyway, sure create a PR with the tests.

**Comment by aolszowka** [comment]
Yup for sure; I'm on the LTS (22.04 Jammy Jellyfish).

I've opened up a Pull Request with the test programs :)

**Comment by vestervang** [comment]
Awesome, I'll close this issue.
